### PR TITLE
Add function to plot grid, line and point data

### LINKED ISSUE #68: Plotting function to plot grid, line and point data in one function call
**Is your feature request related to a problem? Please describe.** 

The code that is needed for plotting radar, gauge and CML data on a map is typically quite long. We have added some nice functions in `poligrain` to make plotting CML paths easiert. However, we have not made is simpler to plot all sensors at once, which is something we often do when looking at merging data and results.

**Describe the solution you'd like** 

We should add xarray Accessors for plotting point and grid data, similar to what we did for lines.

But most importantly we should add a function like this one:

```python

plot_data_on_map(da_grid, da_line, da_point, some_kwargs):
    # all plotting should use some cmap
    da_grid.plg.plot_map(....)
    ...
    return some_fig_object
```

**Additional context** 

A good example where this function will come in handy is [this notebook in `mergeplg`](https://github.com/OpenSenseAction/mergeplg/blob/ad246b92450ae1fe8487f34bc7355728e5246d17/docs/notebooks/openMRG_case_highlevel.ipynb) where the plotting code has a lot of redundancy.

### PR DESCRIPTION
**Pull request by cchwala**
- [x] closes #68 
- [x] Tests added and passed if fixing a bug or adding a new feature
- [x] All code checks from pre-commit passed
- [x] Added an entry in the CHANGELOG.md file

### CODE REVIEW

**Comment by cchwala** [comment]
@eoydvin I have an almost finished plotting function that will make our notebooks in `mergeplg` much shorter by providing one function to plot radar, CML and gauge data all at once and with (hopefully) sane defaults. It would be great if you could have a look at the usage of the function, mainly at the bottom of [this notebook](https://poligrain--75.org.readthedocs.build/en/75/notebooks/Plotting.html) which is part of the this PR. 

Any recommendations regarding default parameters (color map, size of points and lines, width of edge line around point and line)?

I still need to clean up the code and bit and add test. But, given that you do not have major concerns, this would be soon ready to be merged.

**Comment by cchwala** [comment]
There is now a Segmentation Fault on CI, in test and code that I did not touch... 

see https://github.com/OpenSenseAction/poligrain/actions/runs/11506592045/job/32030939231?pr=75

This seems to be caused by frequently opening the same NetCDF file, many test function do this, but we never explicitly close the Dataset and this seems to build up to something that cause the seg fault, see also https://github.com/pydata/xarray/issues/8289 and several other similar issues.

The simplest solution now seems to be to call `ds.close()` at the end of each test function...

**Comment by eoydvin** [comment]
Nice functionalities. I do not have any  major concerns regarding the usage and default parameters. Beware that I have not looked at the underlying code and tests in detail.

**Comment by cchwala** [comment]
Thanks for the feedback. I am quite confident that the code is good. The tests are just calling the functions to see if that still works, because validating that the content of the generated plots is really cumbersome and not really worth it since a user immediately sees that the plotting function does not work correctly (in contrast to processing function) when generating a plot.

Hence, to be able to release a new version that can be installed via pip, I am merging this now.

**Comment by cchwala** [comment]
...but before, I need to finalize the docstring... 🙈

**Pull request merged**
