### PR TITLE
Add grid intersection code 

### LINKED ISSUE #5: Calculate intersection weights of line and grid
This feature should implement the [grid intersection code from pycomlink](https://github.com/pycomlink/pycomlink/blob/master/pycomlink/spatial/grid_intersection.py) that calculates the weights from CML paths over a radar grid. It also should return the radar-along-CML time series calculated from the intersection weights.

There should be a function to get the grid intersection weights, one to calculate the radar_along_CML time series as well as simple options/functions to save or load intersection weights. 

It could be discussed if similar code doing the same with point and grid e.g. from [wradlib](https://wradlib.org/) should be implemented along with this feature.

Todos:

- [ ] Check if not ascending grid coordinates lead to an error in [`calc_sparse_intersect_weights_for_several_cmls()`](https://github.com/pycomlink/pycomlink/blob/94b612c0b0b10219ac8251b1e47afb690bdb56eb/pycomlink/spatial/grid_intersection.py#L12). If so, there is the need for a function that checks and transposes the grid prior to calculating the intersection weights - see [comment](https://github.com/OpenSenseAction/poligrain/issues/5#issuecomment-1921039609) below
- [ ] `get_grid_time_series_at_intersections()` requires the dimension time in its [pycmolink implementation](https://github.com/pycomlink/pycomlink/blob/94b612c0b0b10219ac8251b1e47afb690bdb56eb/pycomlink/spatial/grid_intersection.py#L317) but single time steps without time dimension should be supported

### PR DESCRIPTION
**Pull request by maxmargraf**
This PR should add the calculation of the weights of the grid intersections between line and grid from [pycomlink](https://github.com/pycomlink/pycomlink/blob/master/pycomlink/spatial/grid_intersection.py#L85) to close #5.

- [x] closes #5 
- [x] Tests added and passed if fixing a bug or adding a new feature
- [x] All code checks from pre-commit passed
- [x] Added an entry in the CHANGELOG.md file

### CODE REVIEW

**Comment by maxmargraf** [comment]
To overcome the issue of descending lon/lat coordinates there should be a check based on [this raise](https://github.com/pycomlink/pycomlink/blob/94b612c0b0b10219ac8251b1e47afb690bdb56eb/pycomlink/spatial/grid_intersection.py#L269) that checks if lon or lat are descending and if true, a flip along the respective axes e.g. like [here](https://github.com/pydata/xarray/discussions/6695).

**Comment by maxmargraf** [comment]
* We should raise an error in [`calc_intersect()`](https://github.com/pycomlink/pycomlink/blob/94b612c0b0b10219ac8251b1e47afb690bdb56eb/pycomlink/spatial/grid_intersection.py#L85) if lat or lon coords are not ascending (like its correctly raised right know in [`_calc_grid_corners_for_lower_left_location()`](https://github.com/pycomlink/pycomlink/blob/94b612c0b0b10219ac8251b1e47afb690bdb56eb/pycomlink/spatial/grid_intersection.py#L250). The error should add a code snippet how to flip on or lat OR we add an option to automatically flip the coords to be ascending BUT we happens if we have a grid over the equator and on the southern hemisphere?
--> what do we do with a global grid with lower left definition of the grid??

* Additionally, the offset for the bounding box should be calculated in the center of the grid and should be always positive

**Comment by maxmargraf** [comment]
Summary of recent changes:
* mainly updating the style of the grid intersection and test code
* updating the projects `.toml` file
* removing `pixel_poly_list`
* adding some additional tests for full coverage

Open to suggestions but ready to be merged from my side-

**Comment by cchwala** [comment]
🎉 Thanks @maxmargraf

**Pull request merged**
