### PR TITLE
Add functions for plotting CML metadata

### PR DESCRIPTION
**Pull request by bwalraven**
Adding a function to make frequency vs. length plots. 

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [x] Tests added and passed if fixing a bug or adding a new feature
- [x] All code checks from pre-commit passed
- [x] Added an entry in the CHANGELOG.md file

### CODE REVIEW

**Comment by bwalraven** [comment]
I added a simple notebook example to complete the issue for now. It runs without errors locally and I was able to merge my branch with the main that I forked, but somehow the checks above are not successful. Not sure how to interpret or fix the failed checks. 
@cchwala perhaps you know?

**Comment by cchwala** [comment]
I ran into the same errors during CI runs, see my latest comments and commits in #41.

You have to configure pytest so that it ignores the `ResourceWarning`. You should do it like I did here

https://github.com/OpenSenseAction/poligrain/blob/cc6babfa3f75a9a5f0fe7673cae6eac0f23dfd42/pyproject.toml#L83

**Comment by cchwala** [comment]
@bwalraven Are there some things you want to add to this PR before it get's merged? Since no other PR currently depends on your PR, you could still use the time till the meeting next week to add some things you have in mind. It would be enough to merge next Tuesday. But I can also merge now.

**Comment by bwalraven** [comment]
Okay, I'll try to add some functionalities before Tuesday then and give a heads up when you can merge.

**Comment by bwalraven** [comment]
@cchwala I added a few other functions to plot some meta data. It passed all the tests so it should ready for merge. 

I did have to go back and forth between GH and my local set up to fix some errors that didn't show up when I ran it locally, but raised an error when wanting to merge on GH. Any ideas how to fix this? Or make my set up such that the errors are raised locally as well? This would allow me to catch errors before pushing to GH every time.

**Comment by cchwala** [comment]
> Any ideas how to fix this? Or make my set up such that the errors are raised locally as well?

The `RuntimeWarning` from `matplotlib` because of too many open figures maybe depends on local config. So it is different on CI and you machine. Anyway it is just a warning. But warning let tests fail, unless explicitly allowed.

I am not sure why the `assert all(isinstance(patch, PathCollection) for patch in patches)` passes on your machine but failed on CI. This might stem from using Python version < 3.9 on your machine, but I am not sure.

It is indeed annoying to debug failing test that only fail on CI... We can have a look at your setup tomorrow so see if I can spot something that can be improved.

**Comment by cchwala** [comment]
I just added some minor changes and merge it now. Thanks for this extended contribution 👍

**Pull request merged**
